### ISSUE TITLE
Angabe einer Open Source Lizenz

### ISSUE THREAD

**Issue by mayrstefan** [nick81nrw/PVTools#20]
Nach dem Hinweis im [YT-Video](https://www.youtube.com/watch?v=BWBkrNMinAo) von Andreas auf die Open Source Software sollte auch eine entsprechende Open Source-Lizenz für das Projekt verwendet werden. Unter welchen Bedingungen darf denn mit diesem Code gearbeitet werden?

**Comment by nick81nrw** [comment]
Keine Ahnung, kenne mich da nicht so aus. Code kann frei von allen genutzt und verändert werden. Vielleicht mit dem Hinweis auf den Verfasser

**Comment by mayrstefan** [comment]
Dann wäre ja vielleicht eine [Create Commons Lizenz](https://creativecommons.org/share-your-work/cclicenses/) ganz passend. Deiner Anforderung nach wäre es z.B. eine [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.de).

**Comment by mayrstefan** [comment]
Das Backend scheint gemäß der package.json unter der ISC-Lizenz zu stehen. Allerdings habe ich das Gefühl, dass diese Komponente aus einem anderen Projekt kopiert und minimal modifiziert wurde. Wenn ich es richtig verstanden habe wird es nur für zwei URLs verwendet um den CORS-Header zu entfernen. Für die OSM-URL wäre das Relay technisch sogar nicht notwendig.  Das könnte als GET direkt gegen die OSM-URL realisiert werden. Damit bleibt nur die europa.eu-URL deren CORS-Header im Response nicht passt.
Vom Gefühl würde ich vermuten man kann das auch durch einen nginx Reverse-Proxy mit einer passenden Konfiguration ersetzen. Wie wird das denn auf eurer Website in Produktion verwendet?

**Comment by albertlast** [comment]
Würde es einfach auf MIT setzen,
gibt halt entsprechende Vorlage für jägliche lizenzen in github: 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by mayrstefan** [comment]
Die Commit-History zeigt uns, dass im initialen Commit mal die MIT-Lizenz enthalten war: https://github.com/nick81nrw/PVTools/commit/891ab9ea3cb82027e3370007c73276ba1b179401. Die ist auch inhaltlich relativ nahe an der ISC-Lizenz die noch in dem einem Package-File referenziert wird

**Comment by nick81nrw** [comment]
Gerade das Frontend ist ziemlich zusammengewürfelt. 
Könnte mir jemand ein PR für die Lizenz erstellen? Bin da etwas unerfahren. 
Gerne  [Create Commons Lizenz](https://creativecommons.org/share-your-work/cclicenses/) [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.de).

> Wie wird das denn auf eurer Website in Produktion verwendet?

Ein vorgeschalteter nginx reverse proxy (docker) auf dem Server der letsencrypt macht (mehrere Dienste) und vor der App ist ein docker-compose


```
version: "2"

services:
  app:
    image: node:alpine
    user: "node"
    networks:
      - proxy
    working_dir: /home/node/app/backend
    volumes:
      - ./PVTools/:/home/node/app
    expose:
      - "8082"
    command: "npm start"
    restart: always
    environment:
      - VIRTUAL_HOST=xxx
      - VIRTUAL_PORT=8082
      - LETSENCRYPT_HOST=xxx
      - LETSENCRYPT_EMAIL=xxx
      - NODE_ENV=production
      - GOOGLE_ANALYTICS_ID=xxx
networks:
  proxy:
    external: true
```
