### ISSUE TITLE
Aktivieren von Dependabot

### ISSUE THREAD

**Issue by albertlast** [nick81nrw/PVTools#33]
Um das projekt security mäßig sicherer zu machen,
wäre die aktivierung von dependabot eine gute idee.

Zur Zeit hat das Projekt ~5 security issues davon können wohl vier mittels updates gelöst werden.

![grafik](https://github.com/nick81nrw/PVTools/assets/1782906/6003960b-705f-4dca-8b83-e93caaea5359)

Aktivierung kann nicht durch pullrequest realisiert werden.

**Comment by mayrstefan** [comment]
Beispiel für eine .github/dependabot.yml:
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/pvtools"
    schedule:
      interval: "weekly"
    ignore:
      # Block major upgrade of nuxt and its core dependencies
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]
      - dependency-name: "nuxt"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vue"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vue-server-renderer"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vue-template-compiler"
        update-types: ["version-update:semver-major"]
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

Das Upgrade von Nuxt und Vue ist eine größere Baustelle da der Code zwischen den Versionen nicht kompatibel ist.
