### ISSUE TITLE
Aktivieren von Github Actions

### ISSUE THREAD

**Issue by mayrstefan** [nick81nrw/PVTools#38]
Es wäre für das Projekt ein schönes Feature wenn beim push geprüft wird ob die beiden Anwendungen noch sauber gebaut werden können

Beispiel für .github/workflows/build.yml
```yaml
name: Node.js CI

on: [push]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: backend
        run: npm ci
      - name: Compile TypeScript
        working-directory: backend
        run: npm run compile-ts

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        working-directory: pvtools
        run: npm ci
      # TODO: tests need to be fixed first
      # - name: Run tests
      #   working-directory: pvtools
      #   run: npm run test-all
      - name: Generate static frontend
        working-directory: pvtools
        run: npm run generate
```
